### ISSUE TITLE
🐛 task_bot启动报错

### ISSUE THREAD

**Issue by heyb130** [yokonsan/midjourney-api#114]
### 问题简述

启动task_bot 监听报错了

### 复现方式

Traceback (most recent call last):
  File "C:\project\outsource\midjourney-api-master\task_bot.py", line 13, in <module>
    bot.run(BOT_TOKEN)
  File "C:\Users\18224\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\install\anaconda3\envs\python-310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\install\anaconda3\envs\python-310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\18224\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\18224\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\18224\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by Morrya** [comment]
我是win11，python3.11，也遇到了这个问题。即使重新reset bot token，重新授权也不行。

**Comment by Morrya** [comment]
已解决，见#45
