### ISSUE TITLE
引入队列后代码报错，换了台服务器环境还是一样

### ISSUE THREAD

**Issue by augensternHe** [yokonsan/midjourney-api#17]
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    api_app = server.init_app()
  File "/home/civi/midjourney-api/app/server.py", line 12, in init_app
    register_blueprints(_app)
  File "/home/civi/midjourney-api/app/server.py", line 41, in register_blueprints
    from app import routers
  File "/home/civi/midjourney-api/app/routers.py", line 5, in <module>
    from util._queue import taskqueue
  File "/home/civi/midjourney-api/util/_queue.py", line 4, in <module>
    from typing import ParamSpec, Callable, Any, Dict, List, Deque
ImportError: cannot import name 'ParamSpec' from 'typing' (/usr/lib/python3.8/typing.py)

**Comment by augensternHe** [comment]
单独安装了typing也没有用

**Comment by yokonsan** [comment]
> 单独安装了typing也没有用

升级到 python3.10 呢，或者自己去掉类型注解

**Comment by augensternHe** [comment]
把_queque.py里面的
`from typing import ParamSpec, Callable, Any, Dict, List, Deque`
改成
`from typing import Callable, Any, Dict, List, Deque
from typing_extensions import ParamSpec`
可以运行了，pip安装一下typing-extensions==4.3.0

**Comment by yokonsan** [comment]
好的，类型注解不影响代码逻辑的，可以去掉
