### ISSUE TITLE
一直提示超出最大重试次数

### ISSUE THREAD

**Issue by ffcloudy** [yokonsan/midjourney-api#38]
discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\midjourney-api\task\bot\listener.py", line 47, in on_message
    await callback_trigger(trigger_id, trigger_status, message)
  File "C:\Users\Administrator\midjourney-api\task\bot\handler.py", line 38, in callback_trigger
    await callback(CallbackData(
  File "C:\Users\Administrator\midjourney-api\lib\api\callback.py", line 20, in callback
    await fetch(session, CALLBACK_URL, json=data)
  File "C:\Users\Administrator\midjourney-api\util\fetch.py", line 30, in connect_n_times
    raise MaxRetryError("超出最大重试次数")
exceptions.MaxRetryError: 超出最大重试次数
discord上面正常接收到了信息

**Comment by a1120235890** [comment]
同上 如何解决，网络问题已排查过了

**Comment by ffcloudy** [comment]
已解决

**Comment by a1120235890** [comment]
这个回调地址要如何做呢，回调出来的信息是怎样的，我直接回调回127.0.0.1:8062为什么不通呢
