### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by Andy-Ren** [yokonsan/midjourney-api#52]
### 问题简述

我按照教程上填写了，用户token，bot token，服务器id，频道ID，也安装好了环境，启动后日志报没有权限；

备注：我没有设置回调地址。

报错信息：
[root@iZt4n7ah8y2rvi0odnvq7lZ midjourney-api]# python task_bot.py 
2023-06-16 13:40:20 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "task_bot.py", line 13, in <module>
    bot.run(BOT_TOKEN)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/discord/client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/discord/client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

### 复现方式

在我这里每次启动都不行

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息
[root@iZt4n7ah8y2rvi0odnvq7lZ midjourney-api]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 8.5.2111
Release:        8.5.2111
Codename:       n/a

[root@iZt4n7ah8y2rvi0odnvq7lZ midjourney-api]# python --version
Python 3.8.8

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by yokonsan** [comment]
麻烦认真填写 issue ，做好基本的自我检查
重复 #45

**Comment by Andy-Ren** [comment]
我确认我是能连上 discord服务器的，同时我也开启了相关的开关，但是就是在discord中看不到消息，也收不到回调消息
