### ISSUE TITLE
🐛 启动python task_bot.py的时候报错

### ISSUE THREAD

**Issue by qq921124136** [yokonsan/midjourney-api#79]
### 问题简述

🐛 启动python task_bot.py的时候报错

### 复现方式

🐛 启动python task_bot.py的时候报错
[2023-08-03 16:57:33] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\Programs\Python\Python310\lib\asyncio\base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "D:\Programs\Python\Python310\lib\asyncio\base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "D:\Programs\Python\Python310\lib\asyncio\base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 705, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\Programs\Python\Python310\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "D:\Programs\Python\Python310\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cosmagn-102\Desktop\pythoncode\midjourney-api-master\task_bot.py", line 15, in <module>
    bot.run(BOT_TOKEN)
  File "D:\Programs\Python\Python310\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "D:\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\Programs\Python\Python310\lib\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "D:\Programs\Python\Python310\lib\site-packages\discord\client.py", line 777, in start
    await self.login(token)
  File "D:\Programs\Python\Python310\lib\site-packages\discord\client.py", line 612, in login
    data = await self.http.static_login(token)
  File "D:\Programs\Python\Python310\lib\site-packages\discord\http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "D:\Programs\Python\Python310\lib\site-packages\discord\http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "D:\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "D:\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [信号灯超时时间已到]

### 环境信息

-  OS: win11
-  Python: Python 版本号 (`python --310`)
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by xiongbs** [comment]
和你相同的问题，ping不同，ssh不通

**Comment by xiongbs** [comment]
> 和你相同的问题，ping不同，ssh不通

估计是和issue 48一个问题
